Python 3 (#30)
* python3 umad

* move to zsh postinstall

* nibbler and bom

* update README for OS support

* move to same NSLog as nudge

* fix shebang and imports

diff --git a/scripts/postinstall b/scripts/postinstall
--- a/scripts/postinstall
+++ b/scripts/postinstall
@@ -1,7 +1,6 @@
-#!/usr/bin/python
-# encoding: utf-8
+#!/bin/zsh
 #
-# Copyright 2018 Erik Gomez.
+# Copyright 2019-Present Erik Gomez.
 #
 # Licensed under the Apache License, Version 2.0 (the 'License');
 # you may not use this file except in compliance with the License.
@@ -15,102 +14,63 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-'''Loads the UMAD LaunchAgent and LaunchDaemons'''
-import os
-import subprocess
-import sys
-from SystemConfiguration import SCDynamicStoreCopyConsoleUser
+# If you change your daemon and agent file names, update the following two lines
+launch_agent_plist_name='com.erikng.umad'
+launch_daemon_dep_plist_name='com.erikng.umad.check_dep_record'
+launch_daemon_nag_plist_name='com.erikng.umad.trigger_nag'
 
+# Base paths
+launch_agent_base_path='Library/LaunchAgents/'
+launch_daemon_base_path='Library/LaunchDaemons/'
+base_umad_path='Library/umad/'
 
-def getconsoleuser():
-    '''get console user'''
-    cfuser = SCDynamicStoreCopyConsoleUser(None, None, None)
-    return cfuser
+# Load agent if installing to a running system
+if [[ $3 == "/" ]] ; then
+  # Fail the install if the admin forgets to change their paths and they don't exist.
+  if [ ! -e "$3${launch_daemon_base_path}${launch_daemon_dep_plist_name}.plist" ] || "$3${launch_daemon_base_path}${launch_daemon_nag_plist_name}.plist" ] || [ ! -e "$3${launch_agent_base_path}${launch_agent_plist_name}.plist" ]; then
+    echo "LaunchAgent or Daemons missing, exiting"
+    exit 1
+  fi
 
+  # Make the Log path 777 to cheat - do this before loading LaunchAgent
+  /bin/mkdir "$3${base_umad_path}Logs"
+  /bin/chmod -R 777 "$3${base_umad_path}Logs"
 
-def launchctl(*arg):
-    '''Use *arg to pass unlimited variables to command'''
-    cmd = ['/bin/launchctl'] + list(arg)
-    run = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
-    output, err = run.communicate()
-    return output
+  # Attempt to unload the DEP daemon if it's already loaded
+  /bin/launchctl list | /usr/bin/grep $launch_daemon_dep_plist_name
+  if [[ $? -eq 0 ]]; then
+    /bin/launchctl unload "$3${launch_daemon_base_path}${launch_daemon_dep_plist_name}.plist"
+  fi
 
+  # Attempt to unload the nag daemon if it's already loaded
+  /bin/launchctl list | /usr/bin/grep $launch_daemon_nag_plist_name
+  if [[ $? -eq 0 ]]; then
+    /bin/launchctl unload "$3${launch_daemon_base_path}${launch_daemon_nag_plist_name}.plist"
+  fi
 
-def main(argv):
-    '''main postinstall script'''
-    target = argv[3]
-    # Make the Log path 777 to cheat - do this before loading LaunchAgent
-    umad_log_path = os.path.join(target,
-                                 'Library/Application Support/umad/Logs')
-    os.chmod(umad_log_path, 0o777)
+  # Enable the LaunchDaemons
+  /bin/launchctl load "$3${launch_daemon_base_path}${launch_daemon_dep_plist_name}.plist"
+  /bin/launchctl load "$3${launch_daemon_base_path}${launch_daemon_nag_plist_name}.plist"
 
-    lapath = os.path.join(target, 'Library', 'LaunchAgents',
-                          'com.erikng.umad.plist')
-    ldpath1 = os.path.join(target, 'Library', 'LaunchDaemons',
-                           'com.erikng.umad.check_dep_record.plist')
-    ldpath2 = os.path.join(target, 'Library', 'LaunchDaemons',
-                           'com.erikng.umad.trigger_nag.plist')
-    # Fail the install if the admin forgets to change their paths and they
-    # don't exist
-    for item in [lapath, ldpath1, ldpath2]:
-        if os.path.isfile(item):
-            pass
-        else:
-            print 'File does not exist: %s' % item
-            sys.exit(1)
+  # Current console user information
+  console_user=$(/usr/bin/stat -f "%Su" /dev/console)
+  console_user_uid=$(/usr/bin/id -u "$console_user")
 
-    # Load agents and daemons if installing to a running system
-    if target == '/':
-        currentuseruid = getconsoleuser()
-        current_user_uid = str(currentuseruid[1])
-
-        agents = [
-            'com.erikng.umad'
-        ]
-        daemons = [
-            'com.erikng.umad.check_dep_record',
-            'com.erikng.umad.trigger_nag'
-        ]
-
-        # Get the list of launch agents and daemons
-        launch_daemons = launchctl('list')
-        # This is a deprecated command, but until Apple kills it, it is going
-        # to be used
-        launch_agents = launchctl('asuser', current_user_uid, '/bin/launchctl',
-                                  'list')
-
-        # Now let's loop through the list
-        all_agents = [launch_agents, launch_daemons]
-        all_loaded_agents = {}
-        for index, agent in enumerate(all_agents):
-            loaded_agents = []
-            for loaded_agent in agent.split('\n'):
-                tabbed_output = loaded_agent.split('\t')
-                loaded_agents.append(tabbed_output[-1])
-            if index == 0:
-                all_loaded_agents['launch_agents'] = loaded_agents
-            else:
-                all_loaded_agents['launch_daemons'] = loaded_agents
-
-        for item in daemons:
-            if item in all_loaded_agents['launch_daemons']:
-                launchctl('unload', os.path.join(target, 'Library',
-                                                 'LaunchDaemons',
-                                                 item + '.plist'))
-        launchctl('load', ldpath1)
-        launchctl('load', ldpath2)
-        if (currentuseruid[0] is None or currentuseruid[0] == u'loginwindow'
-                or currentuseruid[0] == u'_mbsetupuser'):
-            pass
-        else:
-            for item in agents:
-                # Unload the agent so it can be triggered on re-install
-                if item in all_loaded_agents['launch_agents']:
-                    launchctl('asuser', current_user_uid, '/bin/launchctl',
-                              'unload', lapath)
-            launchctl('asuser', current_user_uid, '/bin/launchctl', 'load',
-                      lapath)
-
-
-if __name__ == '__main__':
-    main(sys.argv)
+  # Only enable the LaunchAgent if there is a user logged in, otherwise rely on built in LaunchAgent behavior
+  if [[ -z "$console_user" ]]; then
+    echo "Did not detect user"
+  elif [[ "$console_user" == "loginwindow" ]]; then
+    echo "Detected Loginwindow Environment"
+  elif [[ "$console_user" == "_mbsetupuser" ]]; then
+    echo "Detect SetupAssistant Environment"
+  else
+    # This is a deprecated command, but until Apple kills it, it is going to be used
+    /bin/launchctl asuser "${console_user_uid}" /bin/launchctl list | /usr/bin/grep 'umad'
+    # Unload the agent so it can be triggered on re-install
+    if [[ $? -eq 0 ]]; then
+      /bin/launchctl asuser "${console_user_uid}" /bin/launchctl unload "$3${launch_agent_base_path}${launch_agent_plist_name}.plist"
+    fi
+    # Load the launch agent
+    /bin/launchctl asuser "${console_user_uid}" /bin/launchctl load "$3${launch_agent_base_path}${launch_agent_plist_name}.plist"
+  fi
+fi
